function handles = add_synced_props(self, container, handles, list)

n_props = size(list, 1);

spacing = 1/n_props;

for p = n_props : -1 : 1

    prop  = list{p,1};
    txt   = list{p,2};
    scale = list{p,3};

    handles.(sprintf('text_%s', prop)) = uicontrol(container,...
        'Style','text',...
        'String',txt,...
        'Units','normalized',...
        'BackgroundColor',handles.figureBGcolor,...
        'Position',[0 (p-1)*spacing 0.3 spacing]);

    name = sprintf('edit__%s', prop);
    handles.(name) = uicontrol(container,...
        'Tag',name,...
        'Style','edit',...
        'String',num2str(self.(prop)),...
        'Units','normalized',...
        'BackgroundColor',handles.editBGcolor,...
        'Position',[0.3 (p-1)*spacing 0.7 spacing],...
        'Callback',@self.callback_update_value,...
        'UserData',scale); % scaling factor GUI -> SI units
    self.(sprintf('ui__%s',prop)) = handles.(name);

    addlistener(self, prop, 'PostSet', @mri_rf_pulse_sim.rf_pulse.base.gui_prop_changed);


end

end % fcn
